### ISSUE TITLE
grpcwebproxy incompatibility with aspnet core

### ISSUE THREAD

**Issue by FabianTerhorst** [improbable-eng/grpc-web#404]
**Versions of relevant software used** 
latest grpcwebproxy binary for osx.

**What happened**
 the http request to the grpc server contains a invalid connection header field.

**What you expected to happen**
 A valid http/2 request.

**How to reproduce it (as minimally and precisely as possible)**:
Start a aspnet core grpc server (0.1.20).
Start the proxy.
Send grpc request from browser to the proxy.
Server will throw a exception:
```
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Request headers contain connection-specific header field.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ValidateHeader(Span`1 name, Span`1 value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.OnHeader(Span`1 name, Span`1 value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.ProcessHeaderValue(IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnByte(Byte b, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.Decode(ReadOnlySequence`1 data, Boolean endHeaders, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.DecodeHeadersAsync(Boolean endHeaders, ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessHeadersFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

```

Line where the exception is throwed: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L1165

**Environment**:
- OS 0sx 10.14.4:

**Comment by johanbrandhorst** [comment]
The grpcwebproxy just uses the Go gRPC stack to make downstream requests. Can you reproduce this issue with a Go gRPC client?

**Comment by johanbrandhorst** [comment]
For the curious: it seems `connection` is a reserved header, and `te` too, but only if it doesn't appear in a trailer.

**Comment by FabianTerhorst** [comment]
No i can't reproduce it with the go grpc client. I have switched to envoy now which is working

**Comment by johanbrandhorst** [comment]
Interesting. Are you setting the `connection` header in the requests from the front-end? I don't think the proxy sets it.

**Comment by FabianTerhorst** [comment]
I only used the generated service method without specifying any options and without any meta data.

**Comment by FabianTerhorst** [comment]
I was able to resolve it by using port 8443 with https instead of 8080 with http on localhost.

**Comment by johanbrandhorst** [comment]
Closing this as it is unlikely to be a bug in the proxy
