### ISSUE TITLE
grpcwebproxy problems - CORS and Go panic

### ISSUE THREAD

**Issue by pieterlouw** [improbable-eng/grpc-web#48]
Hi,
I created a normal gRPC service (not wrapped) based on the exampleserver to test the `grpcwebproxy`.
(Here's the source for the gRPC service: https://gist.github.com/pieterlouw/b773b16bd488ac3441ca32a739edb4e9)

I then run the `grpcwebproxy` with flag ` --backend_addr=localhost:9090`

I start the example typescript and then get the following in the console.log (which look like it's not handling the CORS and there's a HTTP 500):
```
dev-server.js:49 [HMR] Waiting for update signal from WDS...
:8443/examplecom.library.BookService/GetBook Failed to load resource: the server responded with a status of 500 ()
:8443/examplecom.library.BookService/GetBook Failed to load resource: the server responded with a status of 500 ()
localhost/:1 Fetch API cannot load https://localhost:8443/examplecom.library.BookService/GetBook. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:8082' is therefore not allowed access. The response had HTTP status code 500. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.ts:22 getBook.onEnd 13 Response closed without headers BrowserHeaders
:8443/examplecom.library.BookService/QueryBooks Failed to load resource: the server responded with a status of 500 ()
:8443/examplecom.library.BookService/QueryBooks Failed to load resource: the server responded with a status of 500 ()
localhost/:1 Fetch API cannot load https://localhost:8443/examplecom.library.BookService/QueryBooks. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:8082' is therefore not allowed access. The response had HTTP status code 500. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
bundle.js:4889 queryBooks.onEnd 13 Response closed without headers BrowserHeaders
bundle.js:4939 [WDS] Hot Module Replacement enabled.
bundle.js:4943 [WDS] Disconnected!
```
I looked around in the `main.go` and changed the `servingServer` Handler to this: 
```
servingServer := http.Server{
		WriteTimeout: *flagHttpMaxWriteTimeout,
		ReadTimeout:  *flagHttpMaxReadTimeout,
		Handler: http.HandlerFunc(func(resp http.ResponseWriter, req *http.Request) {
			wrappedGrpc.ServeHTTP(resp, req)
			//if wrappedGrpc.IsGrpcWebRequest(req) || wrappedGrpc.IsAcceptableGrpcCorsRequest(req) {
			//	wrappedGrpc.HandleGrpcWebRequest(resp, req)
			//}
			//resp.WriteHeader(http.StatusNotImplemented)
		}),
	}
```

When I rebuild and ran the `grpcwebproxy` and ran the typescript I received the following panic from `grpcwebproxy`: 
`panic: interface conversion: *proxy.frame is not proto.Message: missing method ProtoMessage`

Full trace: 
```
INFO[0000] listening for http_tls on: [::]:8443
INFO[0000] listening for http on: [::]:8080
panic: interface conversion: *proxy.frame is not proto.Message: missing method ProtoMessage

goroutine 46 [running]:
google.golang.org/grpc.protoCodec.marshal(0x867520, 0xc4201baa00, 0xc4201be5b0, 0x934a4, 0x0, 0x1, 0x5fdd7cfcac48351c, 0xb70ce0)
        $GOPATH/src/google.golang.org/grpc/codec.go:73 +0x45
google.golang.org/grpc.protoCodec.Marshal(0x867520, 0xc4201baa00, 0x410dc2, 0xc4201baa60, 0x20, 0x18, 0x8dcec0)
        $GOPATH/src/google.golang.org/grpc/codec.go:88 +0x73
google.golang.org/grpc.(*protoCodec).Marshal(0xbcd258, 0x867520, 0xc4201baa00, 0x8a1980, 0xc4201baa60, 0x0, 0x7f4c6f920960, 0x0)
        <autogenerated>:35 +0x59
google.golang.org/grpc.encode(0xb74c20, 0xbcd258, 0x867520, 0xc4201baa00, 0x0, 0x0, 0x0, 0x0, 0xc4201dce11, 0x1e, ...)
        $GOPATH/src/google.golang.org/grpc/rpc_util.go:254 +0x2f9
google.golang.org/grpc.(*clientStream).SendMsg(0xc4201d4b00, 0x867520, 0xc4201baa00, 0x0, 0x0)
        $GOPATH/src/google.golang.org/grpc/stream.go:352 +0x11a
github.com/mwitkow/grpc-proxy/proxy.(*handler).forwardServerToClient.func1(0xb77020, 0xc4201ba8c0, 0xc4201ac9c0, 0xb77080, 0xc4201d4b00)
        $GOPATH/src/github.com/mwitkow/grpc-proxy/proxy/handler.go:155 +0xb3
created by github.com/mwitkow/grpc-proxy/proxy.(*handler).forwardServerToClient
        $GOPATH/src/github.com/mwitkow/grpc-proxy/proxy/handler.go:160 +0x89
```

Pieter

**Comment by pieterlouw** [comment]
I see there's already a PR  that will fix problems mentioned above : https://github.com/improbable-eng/grpc-web/pull/45
